== Apache Maven Jenkins Environment

This repository contains a Jenkins shared library that defines the abstraction of the Jenkins build environment from the Jenkins build definition.

The Jenkins build definition is mangaged from the shared libraries defined in https://gitbox.apache.org/repos/asf?p=maven-jenkins-lib.git[maven-jenkins-lib.git]

If you want to build the Apache Maven repositories on your own Jenkins infrastructure you will need to define tow shared libraries:

. The first shared library should be a clone of this shared library with the environment specifics modified to match your own Jenkins environment
. The second shared library should be the https://gitbox.apache.org/repos/asf?p=maven-jenkins-lib.git[maven-jenkins-lib.git] that defines the standard Apache Maven build process

If you would like more information on the design of this Jenkinsfile structure see https://www.youtube.com/watch?v=s4w8BX3xi4M[Episode 4] and https://www.youtube.com/watch?v=vfAzhVDxOOk[Episode 5] of Stephen Connolly's "Watch Me Code" series.
